version: '3.1'
services:
  nginx:
    image: nginx:latest
    container_name: 'nginx'
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./:/app
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    links:
      -  php7.4-fpm
    working_dir: /app

  php7.4-fpm:
    image: chialab/php-dev:7.4-fpm
    container_name: 'php7.4-fpm'
    restart: always
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      XDEBUG_CONFIG: 'remote_enable=true remote_host=host.docker.internal'
    links:
      - mysql

  mysql:
    image: mysql
    container_name: 'mysql'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - '3306:3306'
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
